CREATE DATABASE VehiculoDB;
USE VehiculoDB;
CREATE TABLE Propietarios(
	IdPropietario INT PRIMARY KEY IDENTITY(1,1),
	Nombre NVARCHAR(100) NOT NULL,
	Apellido NVARCHAR(100) NOT NULL,
	DUI	VARCHAR(10) NOT NULL,
	Telefono VARCHAR(15) NOT NULL,
	Direccion NVARCHAR(200) NOT NULL
)